widgetTheme=widget-themes/original
primaryColor=#36a9e1
secondaryColor=#86C953
labelColor=#ffffff
hideWhenOffline=
contactMail=behonesttoshine@gmail.com
loadingLabel=იტვირთება...
loginError=Login error
chatHeader=მოგვწერეთ ჩვენ მოგისმენთ
startInfo=გთხოვთ შეავსოთ შემდეგი ველი
widgetWidth=370
widgetHeight=411
widgetOffset=50
mobileBreakpoint=550
maxConnections=5
messageSound=audio/default.mp3
startLabel=დაწყება
backLabel=უკან
initMessageBody=გამარჯობა
initMessageAuthor=honest
chatInputLabel=შეიყვანეთ ტექსტი
timeDaysAgo=დღე (s) ago
timeHoursAgo=საათი (s) ago
timeMinutesAgo=წუთი (s) ago
timeSecondsAgo=წამი (s) ago
offlineMessage=ამჟამად არცერთი ოპერატორი საიტზე არაა
toggleSoundLabel=Sound effects
toggleScrollLabel=Auto-scroll
toggleEmoticonsLabel=Emoticons
toggleAutoShowLabel=Auto-show
toggleFullscreenLabel=Toggle fullscreen
endChatLabel=End the chat
endChatConfirmQuestion=Are you sure?
endChatConfirm=Yes
endChatCancel=Cancel
contactHeader=Contact us
contactInfo=All operators are off-line. Use the below form to send us an e-mail with your question.
contactNameLabel=Your name
contactMailLabel=Your e-mail
contactQuestionLabel=Your question
contactSendLabel=Send
contactSuccessHeader=Message sent
contactSuccessMessage=Your question has been sent. Thank you!
contactErrorHeader=Error
contactErrorMessage=There was an error sending your question
headerHeight=55
installed=1
autoShowWidgetAfter=1
autoShowWidget=true
askForMail=false
notificationIcon=img/notification.png
